// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://icsbyljmhvnaqipsmvki.supabase.co';
const SUPABASE_PUBLISHABLE_KEY =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imljc2J5bGptaHZuYXFpcHNtdmtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNzY0MDYsImV4cCI6MjA2OTk1MjQwNn0.WTfl6w9j1B498Sn4GzEoRHg9FKtNvNglV2aw5owlSfc';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
    SUPABASE_URL,
    SUPABASE_PUBLISHABLE_KEY,
    {
        auth: {
            storage: localStorage,
            persistSession: true,
            autoRefreshToken: true,
        },
    },
);
